apiVersion: v1
kind: Secret
metadata:
  name: auth-credential
  labels:
    app: postgres
data:
  POSTGRES_USER: 4oCYZnZsaWtwdnXigJk=
  POSTGRES_PASSWORD: 4oCYdzQxVjRtNnVkM3c1dzB3WmpmS3BEWFFLTUpjMWxoZTLigJk=
  JWT_KEY: c3VwZXItc2VjcmVjdC1qd3QtdmFsdWUtZm9yLW15LWF1dGg=
