apiVersion: v1
kind: Secret
metadata:
  name: cart-credential
  labels:
    app: postgres
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  JWT_KEY: c3VwZXItc2VjcmVjdC1qd3QtdmFsdWUtZm9yLW15LWF1dGg=
