apiVersion: v1
kind: Secret
metadata:
  name: cart-credential
  labels:
    app: postgres
data:
  POSTGRES_USER: 4oCYbHBvb2ttbXPigJk=
  POSTGRES_PASSWORD: 4oCYTEdSNDI5X3R1ZEpxYlRMTGd2N2s0Vi03ZkZTdHpqMTjigJk=
  JWT_KEY: c3VwZXItc2VjcmVjdC1qd3QtdmFsdWUtZm9yLW15LWF1dGg=
