apiVersion: skaffold/v2beta6
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
      - ./k8s/secret/*
      - ./k8s/config/*
build:
  local:
    push: false
  artifacts:
    - image: souravdeveloper/ecom-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: souravdeveloper/ecom-cart
      context: cart
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: souravdeveloper/ecom-product
      context: product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
