apiVersion: skaffold/v2beta6
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
      - ./k8s/secret/*
      - ./k8s/volumes/*
      - ./k8s/config/*
build:
  local:
    push: false
  artifacts:
    - image: souravdeveloper/ecom-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: souravdeveloper/ecom-product
      context: product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: souravdeveloper/ecom-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/**/*.tsx'
            dest: .
          - src: 'src/**/*.css'
            dest: .
          - src: 'src/**/*.scss'
            dest: .
          - src: 'src/**/*.json'
            dest: .

    - image: souravdeveloper/ecom-seller-client
      context: seller-client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.jsx'
            dest: .
          - src: '**/*.css'
            dest: .
          - src: '**/*.json'
            dest: .
