apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: souravdeveloper/ecom-product
          envFrom:
            - secretRef:
                name: secret-credential
            - configMapRef:
                name: app-config
          env:
            - name: DB_URL
              value: mongodb+srv://sourav:<password>@cluster0.ut3zhsv.mongodb.net/product?retryWrites=true&w=majority
---
apiVersion: v1
kind: Service
metadata:
  name: product-srv
spec:
  selector:
    app: product
  type: ClusterIP
  ports:
    - name: product
      targetPort: 4000
      port: 4000
      protocol: TCP
