import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Sidebar } from '../components';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Seller Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Sidebar>
          <h2>Home</h2>
        </Sidebar>
      </main>
    </div>
  );
}
